### ISSUE TITLE
Why are readings different from that of pi_ina219

### ISSUE THREAD

**Issue by kramer65** [JeffAlyanak/goina219#2]
Hi and thanks for creating this repo. It's exactly what I need for an autonomous boat project. The code runs great and it gives results. But when I compare it with the readings I get from some Python code I get different results. In the screenshot below you see the simultaneous output of the Go code left, and the Python code right.

![Schermafdruk van 2020-04-01 22-02-23](https://user-images.githubusercontent.com/596581/78181367-8713e100-7464-11ea-8281-182a85c4eea1.png)

For the Go code I used the exact [example code from this repo](https://github.com/JeffAlyanak/goina219/blob/master/example/main.go) (to which I only added a `time.Sleep()`) and I pasted the Python code below.

Would you have any idea where these different current outputs come from?

```
from time import sleep
from ina219 import INA219

ina = INA219(shunt_ohms=0.1,
             max_expected_amps = 0.6,
             address=0x40)

ina.configure(voltage_range=ina.RANGE_16V,
              gain=ina.GAIN_AUTO,
              bus_adc=ina.ADC_128SAMP,
              shunt_adc=ina.ADC_128SAMP)

while True:
    v = ina.voltage()
    i = ina.current()
    p = ina.power()
    print(f"Power: {p/1000}w, Current: {i}mA Voltage: {v}v")
    sleep(1)
```

**Comment by JeffAlyanak** [comment]
@kramer65 Are you certain that the shunt value and configuration settings are identical between the two?

**Edit**: Just saw that you're using my example code without any alteration.

So, the differences are explained by a difference in the config settings and in the shunt resistance value.

In my example, the shunt resistance is set to 0.001Ω. In your Python example it's 0.1Ω. Also, the Python example sets the gain mode to auto, which may or may not select the same gain mode as my example code.

In addition, the Python code uses the 12-bit, 8 sample mode whereas my example is using the 12-bit, single sample continuous mode. Those mode settings won't necessarily make a big difference aside from potentially smoothing transients in your signal.

**Comment by JeffAlyanak** [comment]
I'm closing this issue for now as it's apparent that the issue was related to incorrect setting values.

@kramer65 Feel free to reach out if you have any questions about how the settings should be configured.

**Comment by kramer65** [comment]
For any future readers. I found that when running two programs which read out the same sensor, they can influence eachother. Therefore, always run programs which read out the same thing separately.

In the end I tried https://periph.io/device/ina219/ which worked better, since it gave the same results as my multimeter.
